version: '3'
services:
  postgres:
    image: 'postgres:10.7-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/socialbook_api'
    env_file:
      - '.env'
volumes:
  postgres: